#!/bin/bash 

declare -A color=( ["green"]='\033[0;32m' ["no_color"]='\033[0m' ["white"]='\033[1;37m' ["black"]='\033[0;30m' ["red"]='\033[0;31m' ["orange"]='\033[0;33m' ["yellow"]='\033[1;33m' ["blue"]='\033[0;34m' ["purple"]='\033[0;35m' )
banner="figlet <0>"

if [ -z $1 ];
then
 echo -e "Indicate path to the directory to be watched \n Example: \n dir_watch ./ex/"
 exit
fi

while true
do
 path=$(echo "$(dirname $(readlink -e $1))/$(basename $1)")
 echo -ne "${color[white]}"
$banner
 echo -e "Watching directory: ${color[yellow]} $path \n -------------------  ${color[no_color]}"
 ls -l $1
 sleep 0.5s

 clear
done

