#!/bin/bash 
#!/bin/bash
#Colors ------
GRN='\033[0;32m'
NC='\033[0m'
WH='\033[1;37m'
BLK='\033[ 0;30m'
RED='\033[0;31m'           
ORA='\033[0;33m'       
YEL='\033[1;33m'
BL='\033[0;34m'     
PUR='\033[0;35m'     
LBL='\033[0;36m'    
# ----------------------
echo -ne "${YEL}--Enter sudo password for better experience ${NC}\t"
sudo echo -e "${GRN}Sudo password successfully entered${NC}"
