#!/bin/bash 
GN='\033[0;32m'
NC='\033[0m'
YL='\033[1;33m'
BL='\033[0;36m'
WH='\033[1;37m'
modebat="Discharging"
state=$(acpi | cut -d' ' -f3 | cut -d',' -f1)
disk=$(df -h 2> /dev/null | grep /dev/sda3 | cut -d' ' -f8)
free=$(df -h 2> /dev/null | grep /dev/sda3 | cut -d' ' -f13)
used=$(df -h 2> /dev/null | grep /dev/sda3 | cut -d' ' -f11)
#--- 
echo -e "${WH}___________          ___.           _________ __          __          
\__    ___/_ ________\_ |__   ____ /   _____//  |______ _/  |_  ____  
  |    | |  |  \_  __ \ __ \ /  _ \_____   \   __\__   \   __\/ __ \ 
  |    | |  |  /|  | \/ \_\ (  <_> )        \|  |  / __ \|  | \  ___/ 
  |____| |____/ |__|  |___  /\____/_______  /|__| (____  /__|  \___  >
                          \/              \/           \/          \/ ${NC}"
echo "-------------------------------------------------------------------"
echo -ne "${GN}Battery${NC} is$(acpi | cut -d',' -f2)"
echo -e "\t\t\t From a ${YL}$disk${NC} root directory (/):  "
echo -ne "${YL}Mode:${NC} $state"
echo -e "\t\t	-${YL}$used${NC} used / ${YL}$free${NC} available"


if [ $state == "Discharging" ]; 
then 
hrslft=$(acpi | cut -d' ' -f5 | cut -d':' -f 1)
minlft=$(acpi | cut -d' ' -f5 | cut -d':' -f 2)
echo -e "${YL}Time left:${NC} ${YL}$hrslft${NC} hrs & ${YL}$minlft mins left${NC}"
fi
echo "-------------------------------------------------------------------"
