#!/bin/bash
GREEN='\033[0;32m'
NC='\033[0m'
YELLOW='\033[1;33m'
BLUE='\033[0;36m'   
modebat="Discharging"
battery_percentage(){
number=$(acpi | cut -d',' -f2) 
}
battery_mode(){
state=$(acpi | cut -d' ' -f3 | cut -d',' -f1)
}
battery_percentage
battery_mode
echo " _____________________________ "
echo -e "|    ${BLUE}BatteryCheck-Terminal${NC}    |"
echo "-------------------------------"
echo -e "${GREEN}Battery${NC} is$number"
echo -e "${YELLOW}Mode:${NC} $state"

if [ $state == "Discharging" ]
then 
hrslft=$(acpi | cut -d' ' -f5 | cut -d':' -f 1)
minlft=$(acpi | cut -d' ' -f5 | cut -d':' -f 2)
echo -e "${YELLOW}Time left:${NC} ${YEL}$hrslft${NC} hours and ${YEL}$minlft minutes left${NC}"
fi
echo "-------------------------------"

