#!/bin/bash 
#Colors ------
GRN='\033[0;32m'
NC='\033[0m'
WH='\033[1;37m'
BLK='\033[ 0;30m'
RED='\033[0;31m'           
ORA='\033[0;33m'       
YEL='\033[1;33m'
BL='\033[0;34m'     
PUR='\033[0;35m'     
LBL='\033[0;36m'    
# ----------------------
banner(){
echo '

__________.__  .__       .__     __   
\______   \  | |__| ____ |  |___/  |_ 
 |    |  _/  | |  |/ ___\|  |  \   __\
 |    |   \  |_|  / /_/  >   Y  \  |  
 |______  /____/__\___  /|___|  /__|  
        \/       /_____/      \/      

'
}
menu(){
banner 
menu_grid
usr_term
}
#-------
reload(){
clear
menu
}
#--------
menu_grid(){
blight=$(light)
echo -e "|________________${YEL}OPTIONS${WH}________________|"
echo -e "|${GRN}1.${WH}Set brightness to 5%                 |----> Actual Brightness level: $blight"
echo -e "|${GRN}2.${WH}Set brightness to 25%                |"
echo -e "|${GRN}3.${WH}Set brightness to 50%                |"
echo -e "|${GRN}4.${WH}Set brightness to 75%                |"
echo -e "|${GRN}5.${WH}Set brightness to 100%               |"
echo -e "|${GRN}6.${WH}Set brightness to your desire        |"
echo -e "|${GRN}7.${WH}Refresh                              |"
echo -e "|${GRN}8.${WH}Exit                                 |"
echo -e "|---------------------------------------|"
}
#------- 
usr_term() {
read -p "Type the correspondent number:" ans
case "$ans" in 
1) 
sudo light -S 5
reload 
;;
2)
sudo light -S 25
reload 
;;
3)
sudo light -S 50
reload 
;;
4) 
sudo light -S 75
reload
;;
5) 
sudo light -S 100
reload
;;
6)
read -p "	Type the number you want the brightness to be: " var
sudo light -S $var
reload
;;
7)
reload 
;;
8)
echo -ne "${NC}"
clear 
exit

;;
*)
echo -e "${YEL}Please enter a valid number${NC}"
sleep 1s
reload
;;
esac 
}


menu
