#!/bin/bash
#Colors ------
GRN='\033[0;32m'
NC='\033[0m'
WH='\033[1;37m'
BLK='\033[ 0;30m'
RED='\033[0;31m'           
ORA='\033[0;33m'       
YEL='\033[1;33m'
BL='\033[0;34m'     
PUR='\033[0;35m'     
LBL='\033[0;36m'    
# ----------------------
disk=$(df -h 2> /dev/null | grep /dev/sda3 | cut -d' ' -f8)
free=$(df -h 2> /dev/null | grep /dev/sda3 | cut -d' ' -f13)
used=$(df -h 2> /dev/null | grep /dev/sda3 | cut -d' ' -f11)
echo " _____________________________ "
echo -e "|      ${PUR} FreeSpaceScript${NC}        |"
echo "-------------------------------"
echo -e "From a ${YEL}$disk${NC} root directory (/):  "
echo -e "	-${YEL}$used${NC} are being used"
echo -e "	-And ${YEL}$free${NC} are available"
echo "-------------------------------"

