#!/bin/bash 
#Colors ------
GRN='\033[0;32m'
NC='\033[0m'
WH='\033[1;37m'
BLK='\033[ 0;30m'
RED='\033[0;31m'           
ORA='\033[0;33m'       
YEL='\033[1;33m'
BL='\033[0;34m'     
PUR='\033[0;35m'     
LBL='\033[0;36m'    
# ----------------------
interface=wlan0
echo -e "${YEL}Intitiating...${NC}"
clear

banner() {
echo -ne "${GRN}"
echo ' __      __.__.__   _____.__     _____                                             
/  \    /  \__|  |_/ ____\__|   /     \ _____    ____ _____     ____   ___________ 
\   \/\/   /  |  |\   __\|  |  /  \ /  \\__  \  /    \\__  \   / ___\_/ __ \_  __ \
 \        /|  |  |_|  |  |  | /    Y    \/ __ \|   |  \/ __ \_/ /_/  >  ___/|  | \/
  \__/\  / |__|____/__|  |__| \____|__  (____  /___|  (____  /\___  / \___  >__|   
       \/                             \/     \/     \/     \//_____/      \/       '
echo -ne "${NC}"
echo -e "${WH}---------------------------------------------------------------------------"
}
#--------
menu_grid(){
wifi_state=$(nmcli dev status 2> /dev/null | grep $interface | cut -d' ' -f10)
wifi_con_to=$(nmcli dev status 2> /dev/null | grep wlan0 | cut -d' ' -f12)
echo -e "|________________${YEL}OPTIONS${WH}________________|-----> Interface: ${YEL}$interface${NC} "
echo -e "|${YEL}0.${WH}Change Interface                     |  ---> Status: ${YEL}$wifi_state${NC}"
echo -e "|${YEL}1.${WH}Turn on Wifi                         |  ---> Connected to: ${YEL}$wifi_con_to ${NC}"
echo -e "|${YEL}2.${WH}Turn off Wifi                        |"
echo -e "|${YEL}3.${WH}Restart Wifi                         |"
echo -e "|${YEL}4.${WH}Connection's Menu                    |"
echo -e "|${YEL}5.${WH}Refresh page                         |"
echo -e "|${YEL}6.${WH}Exit                                 |"
echo -e "|${YEL}7.${WH}List Interfaces                      |"
echo -e "|---------------------------------------|"
}

menu_grid2(){
wifi_state=$(nmcli dev status 2> /dev/null | grep $interface | cut -d' ' -f17)
wifi_con_to=$(nmcli dev status 2> /dev/null | grep wlan0 | cut -d' ' -f21 2> /dev/null )
echo -e "|_____________${YEL}DEVICE OPTIONS${WH}____________|-----> Interface: ${YEL}$interface${NC} "
echo -e "|${YEL}0.${WH}List Wifi's Available                |  ---> Status: ${YEL}$wifi_state${NC}"
echo -e "|${YEL}1.${WH}Connect to                           |  ---> Connected to: ${YEL}$wifi_con_to ${NC} "
echo -e "|${YEL}2.${WH}Disconnect of                        |  ${YEL}TIP:${WH} Type 'back' in Connect to" 
echo -e "|${YEL}3.${WH}Back to Main Menu                    | 	reload device options."
echo -e "|${YEL}4.${WH}Refresh page                         |"
echo -e "|${YEL}5.${WH}Exit                                 |"
echo -e "|---------------------------------------|"
}



#--------- Administrative 
reload1(){ 
 clear
 menu1
}
reload2(){
clear 
menu2
}

sudo_ask(){
clear
echo -e "${YEL}Sudo password for better experience: ${NC}"
sudo echo -e  "${GRN} Sudo password successfully entered${NC}"
clear
}
#--------
menu1() {
sudo_ask 
banner
menu_grid
usr_term
}
menu2() {
banner
menu_grid2
usr_term2
}
#-------
usr_term(){
read -p "  Type the correspondent number:" input
case "$input" in 
0) #INTERFACE
read -p "   Type the name of the interface you want to use: " interface
reload1
;;
1) #TURNON
echo -e "${YEL}Starting Wifi...${NC}"
sudo systemctl start NetworkManager.service 
sleep 5s
echo -e "${GRN}Wifi Started${NC}"
reload1
;;
2) #TURNOFF 
echo -e "${YEL}Stopping Wifi...${NC}"
sudo systemctl stop NetworkManager.service
echo -e "${GRN}Wifi Stopped${NC}"
sleep 0.5s
reload1 
;;
3) #RESTART
echo -e "${YEL}Restarting Wifi...${NC}"
sudo systemctl restart NetworkManager.service
sleep 5.5s
echo -e "${GRN}Wifi Restarted${NC}"
reload1 
;;
4) #DEVICES 
clear 
menu2
;;
5) #REFRESH 
reload1
;;
6) #EXIT
clear 
echo -e "${GRN} THANKS FOR USING WILFI WIFI MANAGER!${NC}"
exit 
;;
7) #INTERFACE LIST
 clear
 banner 
 menu_grid
 sudo nmcli dev status 2> /dev/null
 echo -ne "${WH}"
 usr_term
;;
*)
echo -e "${YEL}Please enter a valid number ${NC}"
sleep 1s 
reload1
;;
esac
}

usr_term2(){
read -p "  Type the correspondent number:" input2
case "$input2" in 
0) #INTERFACE
 clear
 banner 
 menu_grid2
 echo -e "${YEL}Press 'q' when the search has finished"
 echo -e "Listing...${NC}"
 nmcli dev wifi list
 echo -ne "${WH}"
 usr_term2
;;
1)#CONNECT 
read -p "	Type the SSID of the desired Wifi: " ssid
if [ $ssid == "back" ]
then 
reload2 
fi
read -p "	Type the password: " pass
echo -e "${YEL}Attempting to connect $ssid Wifi...${WH}"
nmcli dev wifi connect $ssid password $pass
echo -ne "${NC}"
reload2 
;;
2) #DISCONNECT 
read -p "       Type the SSID of the desired Wifi: " ssid
nmcli connection down $ssid
echo -e "${YEL}Attempting to disconnect $ssid Wifi...${WH}"
sleep 2.5s
reload2;;
3) #BACK TO MENU
clear 
menu1
;;
4) #REFRESH 
reload2
;;
5) #EXIT
clear 
echo -e "${GRN} THANKS FOR USING WILFI WIFI MANAGER!${NC}"
exit 
;;
*)
echo -e "${YEL}Please enter a valid number ${NC}"
sleep 1s 
reload2
;;
esac 
}
#-----------
#Actual Program
menu1

