#!/bin/bash
#Colors ------
GRN='\033[0;32m'
NC='\033[0m'
WH='\033[1;37m'
BLK='\033[ 0;30m'
RED='\033[0;31m'           
ORA='\033[0;33m'       
YEL='\033[1;33m'
BL='\033[0;34m'     
PUR='\033[0;35m'     
LBL='\033[0;36m'    
# ----------------------
sudo_pass() { #Verification for sudo
echo "SUDO PASSWORD NOT INTRODUCED"
echo "For a better experience, confirm your sudo password to avoid verification during the execution of the script"
sudo echo DONE
clear
}
exit_code() {
clear
echo -e "${LBL} Thanks for using TOOTHY!! ${NC}"
exit
}
#--------------------
banner(){ #Bluetooth status + deco 
blu_status
echo -e "${WH} _______________________________________ "
echo -e "|${BL}                TOOTHY                ${WH} |"
echo -e " --------------------------------------- ${WH}"
echo -e "|       ${WH}Your ${BL}bluetooth ${WH}is $status        |"
}
banner_deco(){ # Just Decoration
echo -e "${WH} _______________________________________ "
echo -e "|${BL}                TOOTHY                ${WH} |"
echo -e " --------------------------------------- ${WH}"
echo -e "|________________${YEL}DEVICES${WH}________________|"
}
#--------------------
blu_status(){
	status=$(sudo systemctl status bluetooth | grep Active: | cut -d' ' -f7)
}
#--------------------
menu_grid(){
echo -e "|________________${YEL}OPTIONS${WH}________________|"
echo -e "|${GRN}1.${WH}Start Bluetooth                      |"
echo -e "|${GRN}2.${WH}Device menu                          |"
echo -e "|${GRN}3.${WH}Stop Bluetooth                       |"
echo -e "|${GRN}4.${WH}Enable Bluetooth                     |"
echo -e "|${GRN}5.${WH}Restart Bluetooth                    |"
echo -e "|${GRN}6.${WH}Refresh                              |"
echo -e "|${GRN}7.${WH}Exit                                 |"
echo -e "|---------------------------------------|"
}
menu_grid2(){
echo -e "|${GRN}0.${WH}Scan Device                          |"
echo -e "|${GRN}1.${WH}Connect Device                       |" 
echo -e "|${GRN}2.${WH}Disconnect Device                    |"
echo -e "|${GRN}3.${WH}List Connected Devices               |" 
echo -e "|${GRN}4.${WH}Back to menu                         |"
echo -e "|${GRN}5.${WH}Refresh                              |"
echo -e "|${GRN}6.${WH}Exit                                 |"
echo -e "|___________${YEL}DEVICES CONNECTED${WH}___________|"
}
#--------------------
menu1(){ #Initial menu
sudo_pass 
banner
menu_grid
user_terminal
}
menu2(){ #Device menu
banner_deco
menu_grid2
bluetoothctl paired-devices
user_terminal2
}
menu2_nterm(){ #Device menu
banner_deco
menu_grid2
bluetoothctl paired-devicess
}
#--------------------
reload () {
clear 
menu1
}
reload2  () {
clear 
menu2
}
#--------------------
user_terminal() {
read -p " Type the correspondent number: " term
case "$term" in 
1) #START bluetooth
echo "Starting Bluetooth..." 
sudo systemctl start bluetooth
echo "Bluetooth started" 
sleep 1s 
reload
;;
2) #Device menu
clear
menu2
;;
3) #STOP bluetooth
echo "Stopping Bluetooth..."
sudo systemctl stop bluetooth
echo "Bluetooth stopped" 
sleep 1s
reload
;;
4) #ENABLE bluetooth (service)
echo "Enabeling Bluetooth"
sudo systemctl enable bluetooth
echo "Bluetooth enabled" 
sleep 1s 
reload
;;
5) #RESTART bluetooth (service)
echo "Restarting bluetooth's service"
sudo systemctl restart bluetooth
echo "Bluetooth restarted"
sleep 1s 
reload
;;
6) #reloading
reload
;;
7) #exiting
exit_code
;;
*) 
echo "Please enter a valid number"
sleep 2s 
reload
;;
esac
}

user_terminal2() {
read -p " Type the correspondent number: " term2
case "$term2" in 
0) #Scan
echo "Whenever you want to stop, press Ctrl+C"
bluetoothctl scan on 
echo -e " ${WH}Scan done!"
user_terminal2
;;
1) #Connect 
read -p "	Copy here the id of your device: " id
bluetoothctl connect $id
sleep 1s
reload2
;;
2) #Disconnect
read -p "	Copy here the id of your device: " id
bluetoothctl disconnect $id
sleep 1s
reload2
;;
3) #List
reload2
;;
4) #Back to main menu
menu1
;;
5) #reloading
reload2
;;
6) #exiting
exit_code
;;
*) 
echo "Please enter a valid number"
sleep 2s
reload2
;;
esac
}
menu1

